services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/sixth-now-475017-k8-785034518ab7.json
      - FLASK_HOST=0.0.0.0

